[package]
name = "rustupr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
command-rs = {path = "../command-rs"}
thiserror = "1.0.28"

[dev-dependencies]
kiruna = {path = "../kiruna", features=["test"]}